/**
 * Created by Zhang Haijun on 2016/8/9.
 */
//数据接口
app.constant('CONFIG', {
	'/login': '/statics/api/access/login.json',
	//退出
	"/logout" : "/statics/api/assets/datacenter/dataCenter-modify.json",
	// 用户修改密码
	"/user/change" : "/statics/api/assets/datacenter/dataCenter-modify.json",   //密码修改
	"/user/check" : "/statics/api/assets/datacenter/dataCenter-modify.json",    //密码校验
	
	'/statics/api/graph/dashborad.json':'/statics/api/graph/dashborad.json',
	'/stats/dashboard':'/statics/api/graph/dashborad.json',
	'/stats/manage':'/statics/api/graph/dashborad.json',
	// 数据中心
	"/dc/list" : "/statics/api/assets/datacenter/dataCenter-list.json",
	"/dc/create" : "/statics/api/assets/datacenter/dataCenter-modify.json",
	"/dc/modify" : "/statics/api/assets/datacenter/dataCenter-modify.json",
	"/dc/remove" : "/statics/api/assets/datacenter/dataCenter-modify.json",
	"/dc/load" : "/statics/api/assets/datacenter/dataCenter-load.json",
	"/dc/basic" : "/statics/api/assets/datacenter/dataCenter-basic.json",
	"/dc/detail" : "/statics/api/assets/datacenter/dataCenter-detail.json",//基本信息

	"/dc/alarms" : "/statics/api/assets/datacenter/warnningServerList.json", //告警服务器列表
	"/dc/topLoad" : "/statics/api/assets/datacenter/warnningServerList.json", //高负载服务器列表

	'/dc/freeClusters' : '/statics/api/assets/datacenter/freeClusters.json',

	"/dc/graph" : "/statics/api/assets/datacenter/graph.json",                 //3d图
	// 机房
	"/room/list" : "/statics/api/assets/room/roomList.json",
	"/room/load" : "/statics/api/assets/datacenter/dataCenter-load.json",
	"/room/create" : "/statics/api/assets/room/roomList.json",
	"/room/modify" : "/statics/api/assets/room/roomList.json",
	"/room/remove" : "/statics/api/assets/room/roomList.json",
	"/room/detail" : "/statics/api/assets/room/roomDetail.json",
	"/room/basic" : "/statics/api/assets/room/roomDetail.json",
	"/room/alarms" : "/statics/api/assets/datacenter/warnningServerList.json", //告警服务器列表
	"/room/topLoad" : "/statics/api/assets/datacenter/warnningServerList.json", //高负载服务器列表

	"/room/graph" : "/statics/api/assets/room/graph.json",                       //3d图
	//分区
	"/zone/list" : "/statics/api/assets/zone/zone-list.json",
	"/zone/create" : "/statics/api/assets/zone/zone-list.json",
	"/zone/modify" : "/statics/api/assets/zone/zone-list.json",
	"/zone/remove" : "/statics/api/assets/zone/zone-list.json",
	"/zone/load" : "/statics/api/assets/datacenter/dataCenter-load.json",
	"/zone/detail" : "/statics/api/assets/zone/zone-detail.json",
	"/zone/basic" : "/statics/api/assets/zone/zone-basic.json",
	"/zone/alarms" : "/statics/api/assets/datacenter/warnningServerList.json", //告警服务器列表
	"/zone/topLoad" : "/statics/api/assets/datacenter/warnningServerList.json", //高负载服务器列表

	"/zone/graph" : "/statics/api/assets/zone/graph.json",                       //3d图
	//机柜
	"/rack/list" : "/statics/api/assets/rack/cabinetList.json",
	"/rack/create" : "/statics/api/assets/rack/cabinetList.json",
	"/rack/modify" : "/statics/api/assets/rack/cabinetList.json",
	"/rack/remove" : "/statics/api/assets/rack/cabinetList.json",
	"/rack/detail" : "/statics/api/assets/rack/cabinetDetail.json",
	"/rack/basic" : "/statics/api/assets/rack/cabinetDetail.json",
	'/rack/load' : '/statics/api/assets/datacenter/dataCenter-load.json',
	"/rack/alarms" : "/statics/api/assets/datacenter/warnningServerList.json", //告警服务器列表

	"/rack/graph" : "/statics/api/assets/rack/graph.json",                       //3d图
	"/rack/freeServers" : '/statics/api/assets/server/serviceList.json',   //游离服务器
	"/dc/freeManagers" : '/statics/api/assets/server/serviceList.json',   //游离服务器
	"/room/freeServers" : '/statics/api/assets/server/serviceList.json',   //游离服务器
	"/paas/host/freeManagers" : '/statics/api/assets/server/serviceList.json',   //游离服务器
	"/paas/host/freeNodes" : '/statics/api/assets/server/serviceList.json',   //游离服务器

	//服务器
	'/server/list' : '/statics/api/assets/server/serverList.json',
	'/rack/resources' : '/statics/api/assets/server/racksList.json',
	'/server/modify' : '/statics/api/assets/server/serverList.json',
	'/server/create' : '/statics/api/assets/server/serverList.json',
	'/server/remove' : '/statics/api/assets/server/serverList.json',
	'/server/detail' : '/statics/api/assets/server/serverDetail.json',
	'/server/basic' : '/statics/api/assets/server/serverDetail.json',
	'/device/network/list' : '/statics/api/assets/server/serverList.json',
	'/device/network/modify' : '/statics/api/assets/server/serverList.json',
	'/device/network/create' : '/statics/api/assets/server/serverList.json',
	'/device/network/remove' : '/statics/api/assets/server/serverList.json',
	'/device/network/detail' : '/statics/api/assets/server/serverDetail.json',
	'/device/network/basic' : '/statics/api/assets/server/serverDetail.json',
	'/device/storage/list' : '/statics/api/assets/server/serverList.json',
	'/device/storage/modify' : '/statics/api/assets/server/serverList.json',
	'/device/storage/create' : '/statics/api/assets/server/serverList.json',
	'/device/storage/remove' : '/statics/api/assets/server/serverList.json',
	'/device/storage/detail' : '/statics/api/assets/server/serverDetail.json',
	'/server/load' : '/statics/api/assets/datacenter/dataCenter-load.json',
	//主机
	'/paas/host/list' : '/statics/api/assets/server/serverList.json',
	'/paas/host/modify' : '/statics/api/assets/server/serverList.json',
	'/paas/host/create' : '/statics/api/assets/server/serverList.json',
	'/paas/host/remove' : '/statics/api/assets/server/serverList.json',
	'/paas/host/detail' : '/statics/api/assets/server/serverDetail.json',
	'/paas/host/basic' : '/statics/api/assets/server/serverDetail.json',
	'/paas/host/load' : '/statics/api/assets/datacenter/dataCenter-load.json',
	//集群A
	'/paas/cluster/list' : '/statics/api/assets/group/groupData.json',
	'/paas/cluster/modify' : '/statics/api/assets/group/groupData.json',
	'/paas/cluster/create' : '/statics/api/assets/group/groupData.json',
	'/paas/cluster/remove' : '/statics/api/assets/group/groupData.json',
	'/paas/cluster/basic' : '/statics/api/assets/group/clusterDetail.json',
	'/paas/cluster/detail' : '/statics/api/assets/group/clusterDetail.json',
	"/paas/cluster/load" : "/statics/api/assets/datacenter/dataCenter-load.json",
	"/paas/cluster/nodes" : "/statics/api/assets/group/nodeData.json",
	"/paas/cluster/managers" : "/statics/api/assets/group/nodeData.json",
	"/paas/cluster/addNode" : "/statics/api/assets/group/nodeData.json",
	"/paas/cluster/delNode" : "/statics/api/assets/group/nodeData.json",
	"/paas/cluster/addManager" : "/statics/api/assets/group/nodeData.json",
	"/paas/cluster/delManager" : "/statics/api/assets/group/nodeData.json",
	"/paas/cluster/isMasterNode" : "/statics/api/assets/group/nodeData.json",
	"/paas/cluster/checkPort" : "/statics/api/assets/group/nodeData.json",
	"/paas/cluster/startNode" : "/statics/api/assets/group/nodeData.json",
	"/paas/cluster/stopNode" : "/statics/api/assets/group/nodeData.json",
	"/paas/cluster/startManager" : "/statics/api/assets/group/nodeData.json",
	"/paas/cluster/stopManager" : "/statics/api/assets/group/nodeData.json",
	//资源池
	'/pool/list' : '/statics/api/assets/pool/poolList.json',
	'/pool/modify' : '/statics/api/assets/pool/poolList.json',
	'/pool/create' : '/statics/api/assets/pool/poolList.json',
	'/pool/remove' : '/statics/api/assets/pool/poolList.json',
	'/pool/basic' : '/statics/api/assets/pool/pool-detail.json',
	'/pool/detail' : '/statics/api/assets/pool/pool-detail.json',
	"/pool/load" : "/statics/api/assets/datacenter/dataCenter-load.json",
	//数据库管理
	'/db/ins/list': '/statics/api/application/applicationList.json',
	'/db/ins/create': '/statics/api/application/applicationList.json',
	'/db/ins/configs': '/statics/api/assets/rack/cabinetDetail.json',
	'/db/ins/sync': '/statics/api/application/applicationList.json',
	'/db/ins/remove': '/statics/api/application/applicationList.json',
	'/db/ins/reboot': '/statics/api/application/applicationList.json',
	'/db/ins/detail' : '/statics/api/config/vmDetail.json',
	'/pdb/list': '/statics/api/application/applicationList.json',
	'/pdb/create': '/statics/api/application/applicationList.json',
	'/pdb/modify': '/statics/api/application/applicationList.json',
	'/pdb/remove': '/statics/api/application/applicationList.json',
	'/pdb/reboot': '/statics/api/application/applicationList.json',
	'/pdb/start': '/statics/api/application/applicationList.json',
	'/pdb/stop': '/statics/api/application/applicationList.json',
	'/pdb/detail' : '/statics/api/config/vmDetail.json',

	"/pool/listRes" : "/statics/api/assets/pool/pool-resource.json",     //资源列表
	"/pool/addRes" : "/statics/api/assets/pool/pool-resource.json",        //加入资源
	"/pool/delRes" : "/statics/api/assets/pool/pool-resource.json",       //移除资源
	//容器
	'/caas/container/list' : '/statics/api/assets/container/list.json',
	'/caas/container/start' : '/statics/api/assets/container/list.json',
	'/caas/container/restart' : '/statics/api/assets/container/list.json',
	'/caas/container/stop' : '/statics/api/assets/container/list.json',
	'/caas/container/detail' : '/statics/api/assets/container/detail.json',
	"/caas/container/load" : "/statics/api/assets/datacenter/dataCenter-load.json",
	"/caas/container/remove" : "/statics/api/assets/datacenter/dataCenter-load.json",
	//镜像管理
	'/image/list' : '/statics/api/assets/image/imageList.json',
	'/image/detail' : '/statics/api/assets/image/image-detail.json',
	'/image/sync' : '/statics/api/assets/datacenter/dataCenter-load.json',
	//块设备管理
	'/volume/list' : '/statics/api/assets/volume/volume-list.json',
	'/volume/create' : '/statics/api/assets/volume/volume-list.json',
	'/volume/remove' : '/statics/api/assets/volume/volume-list.json',
	'/volume/sync' : '/statics/api/assets/volume/volume-list.json',
	'/volume/detail' : '/statics/api/assets/image/image-detail.json',
	//快照管理
	'/snapshot/list' : '/statics/api/assets/snapshot/snapshot-list.json',
	'/snapshot/create' : '/statics/api/assets/snapshot/snapshot-list.json',
	'/snapshot/remove' : '/statics/api/assets/snapshot/snapshot-list.json',
	'/snapshot/sync' : '/statics/api/assets/snapshot/snapshot-list.json',
	'/snapshot/detail' : '/statics/api/assets/image/image-detail.json',
	//配置管理
	'/flavor/list' : '/statics/api/assets/size/size-list.json',
	'/flavor/sync' : '/statics/api/assets/size/size-list.json',
	'/flavor/detail' : '/statics/api/assets/image/image-detail.json',
	//网络管理
	'/network/list' : '/statics/api/assets/network/network-list.json',
	'/network/create' : '/statics/api/assets/network/network-list.json',
	'/network/remove' : '/statics/api/assets/network/network-list.json',
	'/network/sync' : '/statics/api/assets/network/network-list.json',
	'/network/detail' : '/statics/api/assets/image/image-detail.json',
	//子网管理
	'/subnet/list':  '/statics/api/assets/network/network-list.json',
	'/subnet/create' : '/statics/api/assets/network/network-list.json',
	'/subnet/remove' : '/statics/api/assets/network/network-list.json',
	'/subnet/detail' : '/statics/api/assets/subnet/subnet-detail.json',
	//安全组管理
	'/security/group/list' : '/statics/api/assets/network/network-list.json',
	'/security/group/create' : '/statics/api/assets/network/network-list.json',
	'/security/group/remove' : '/statics/api/assets/network/network-list.json',
	'/security/group/sync' : '/statics/api/assets/network/network-list.json',
	'/security/group/detail' : '/statics/api/assets/image/image-detail.json',
	//配额管理
	'/tenant/quota/list' : '/statics/api/assets/tenantQuota/tenantQuotaList.json',
	'/tenant/quota/modify' : '/statics/api/userCenter/user/userList.json',
	'/tenant/quota/create' : '/statics/api/userCenter/user/userList.json',
	'/tenant/quota/remove' : '/statics/api/userCenter/user/userList.json',
	'/tenant/quota/detail' : '/statics/api/assets/image/image-detail.json',
	//存储管理
	//"/storage/list": '/statics/api/assets/storage/storage.json',
	'/bucket/list': '/statics/api/assets/storage/bucket.json',
	'/bucket/create' : '/statics/api/assets/network/network-list.json',
	'/bucket/remove' : '/statics/api/assets/network/network-list.json',
	'/bucket/sync' : '/statics/api/assets/network/network-list.json',
	'/bucket/detail' : '/statics/api/assets/storage/bucket-detail.json',
	//中间件管理
	'/middleware/list':'/statics/api/assets/middleware/middleware.json',
	'/middleware/create':'/statics/api/assets/middleware/middleware.json',
	'/middleware/modify':'/statics/api/assets/middleware/middleware.json',
	'/middleware/remove':'/statics/api/assets/middleware/middleware.json',
	'/middleware/detail':'/statics/api/assets/middleware/middleware-detail.json',
	//用户管理
	'/user/list' : '/statics/api/userCenter/user/userList.json',
	'/user/modify' : '/statics/api/userCenter/user/userList.json',
	'/user/create' : '/statics/api/userCenter/user/userList.json',
	'/user/remove' : '/statics/api/userCenter/user/userList.json',
	'/user/detail' : '/statics/api/userCenter/user/userDetail.json',
	'/user/checkUsername' : '/statics/api/assets/datacenter/dataCenter-modify.json',

	'/user/lock' : '/statics/api/userCenter/user/userList.json',
	'/user/active' : '/statics/api/userCenter/user/userList.json',
	'/user/reset' : '/statics/api/userCenter/user/userList.json',
	'/user/auth' : '/statics/api/userCenter/role/roleList.json',
	'/user/roles' : '/statics/api/userCenter/role/roleList.json',
	'/user/accredit' : "/statics/api/assets/datacenter/dataCenter-load.json",
	'/user/quota' : '/statics/api/userCenter/role/roleList.json',
	'/user/res' : '/statics/api/userCenter/department/distribute.json',
	'/user/assign':'/statics/api/userCenter/department/distribute.json',
	'/user/deleteRes':'/statics/api/userCenter/department/distribute.json',
	//角色管理
	'/role/list' : '/statics/api/userCenter/role/roleList.json',
	'/role/modify' : '/statics/api/userCenter/role/roleList.json',
	'/role/create' : '/statics/api/userCenter/role/roleList.json',
	'/role/remove' : '/statics/api/userCenter/role/roleList.json',
	'/role/detail' : '/statics/api/userCenter/role/roleDetail.json',
	'/role/auth' : '/statics/api/userCenter/permission/permissionList.json',
	'/role/auths': '/statics/api/userCenter/permission/permissionList.json',
	'/role/accredit': '/statics/api/assets/datacenter/dataCenter-load.json',
	'/role/commands': '/statics/api/userCenter/permission/permissionList.json',
	'/role/accCommand': '/statics/api/assets/datacenter/dataCenter-load.json',
	//权限管理
	'/auth/list' : '/statics/api/userCenter/permission/permissionList.json',
	'/auth/remove' : '/statics/api/userCenter/permission/permissionList.json',
	'/auth/create' : '/statics/api/userCenter/permission/permissionList.json',
	'/auth/modify' : '/statics/api/userCenter/permission/permissionList.json',
	'/auth/detail' : '/statics/api/userCenter/permission/permissionDetail.json',
	'/auth/listParents':'/statics/api/userCenter/permission/permissionList.json',
	'/auth/list/icon':'/statics/api/userCenter/permission/permissionList.json',
	//租户管理
	'/tenant/list' : '/statics/api/userCenter/tenant/tenantList.json',
	'/tenant/modify' : '/statics/api/userCenter/tenant/tenantList.json',
	'/tenant/create' : '/statics/api/userCenter/tenant/tenantList.json',
	'/tenant/remove' : '/statics/api/userCenter/tenant/tenantList.json',
	'/tenant/detail' : '/statics/api/userCenter/tenant/tenantDetail.json',
	'/tenant/checkTenant' : '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/tenant/auths' : '/statics/api/userCenter/permission/permissionList.json',
	'/tenant/accredit': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/tenant/lock' : '/statics/api/userCenter/permission/permissionList.json',
	'/tenant/active' : '/statics/api/userCenter/permission/permissionList.json',
	'/tenant/users' : '/statics/api/userCenter/user/userList.json',
	'/tenant/roles' : '/statics/api/userCenter/role/roleList.json',
	'/tenant/quota' : '/statics/api/userCenter/role/roleList.json',
	'/tenant/res' : '/statics/api/userCenter/department/distribute.json',
	'/tenant/assign':'/statics/api/userCenter/department/distribute.json',
	'/tenant/deleteRes':'/statics/api/userCenter/department/distribute.json',
	'/tenant/vendor': '/statics/api/userCenter/tenant/vendor.json',
	//组织机构
	'/department/list' : '/statics/api/userCenter/department/departmentList.json',
	'/department/remove' : '/statics/api/userCenter/department/departmentList.json',
	'/department/create' : '/statics/api/userCenter/department/departmentList.json',
	'/department/modify' : '/statics/api/userCenter/department/departmentList.json',
	'/department/detail' : '/statics/api/userCenter/department/departmentDetail.json',
	'/department/quota' : '/statics/api/userCenter/role/roleList.json',
	'/department/res' : '/statics/api/userCenter/department/distribute.json',
	'/department/assign':'/statics/api/userCenter/department/distribute.json',
	'/res/list' : '/statics/api/userCenter/department/distribute.json',
	'/department/deleteRes':'/statics/api/userCenter/department/distribute.json',
	//分组管理
	'/user/group/list' : '/statics/api/userCenter/user/userList.json',
	'/user/group/remove' : '/statics/api/userCenter/user/userList.json',
	'/user/group/create' : '/statics/api/userCenter/user/userList.json',
	'/user/group/modify' : '/statics/api/userCenter/user/userList.json',
	'/user/group/detail' : '/statics/api/userCenter/group/groupDetail.json',
	'/user/group/users': '/statics/api/userCenter/user/userList.json',
	'/user/group/addUser': '/statics/api/userCenter/user/userList.json',
	'/user/group/resGroups':'/statics/api/userCenter/user/userList.json',
	'/user/group/addResGroup':'/statics/api/userCenter/user/userList.json',
	'/user/group/listUser': '/statics/api/userCenter/group/group.json',
	'/user/group/listResGroup': '/statics/api/userCenter/group/group.json',

	'/res/group/list' : '/statics/api/userCenter/user/userList.json',
	'/res/group/remove' : '/statics/api/userCenter/user/userList.json',
	'/res/group/create' : '/statics/api/userCenter/user/userList.json',
	'/res/group/modify' : '/statics/api/userCenter/user/userList.json',
	'/res/group/detail' : '/statics/api/userCenter/group/groupDetail.json',
	'/res/group/addRes': '/statics/api/userCenter/user/userList.json',
	'/res/group/listRes':'/statics/api/userCenter/group/group.json',
	//系统字典
	'/dict/list' : '/statics/api/config/dictionaryList.json',
	'/dict/children' : '/statics/api/config/dictionaryList.json',
	//脚本管理
	'/script/list': '/statics/api/operation/scriptList.json',
	'/script/create': '/statics/api/operation/account.json',
	'/script/modify': '/statics/api/operation/account.json',
	'/script/remove': '/statics/api/operation/account.json',
	'/script/detail': '/statics/api/operation/scriptvalues.json',
	'/script/group/listAll':'/statics/api/config/scriptGroupList.json',
	//脚本分组管理
	'/script/group/list': '/statics/api/config/scriptGroupList.json',
	'/script/group/create': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/script/group/modify': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/script/group/remove': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/script/group/detail' : '/statics/api/config/scriptGroup-detail.json',
	//软件管理
	'/software/list': '/statics/api/config/software.json',
	'/software/listAll': '/statics/api/config/softwares.json',
	'/software/create': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/software/modify': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/software/remove': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/software/detail' : '/statics/api/config/software-detail.json',
	'/software/group/listAll' : '/statics/api/config/softwareGroup.json',
	'/software/download':'/statics/api/assets/datacenter/dataCenter-modify.json',
	//软件分组管理
	'/software/group/list': '/statics/api/config/softwareGroup.json',
	'/software/group/create': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/software/group/modify': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/software/group/remove': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/software/group/detail' : '/statics/api/config/softwareGroup-detail.json',
	//认证管理
	'/ident/list': '/statics/api/config/identList.json',
	'/ident/create': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/ident/modify': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/ident/remove': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/ident/detail' : '/statics/api/config/ident-detail.json',
	//云供应商管理
	"/cloudVendor/list": '/statics/api/config/supplier.json',
	'/cloudVendor/create': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/cloudVendor/modify': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/cloudVendor/remove': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/cloudVendor/detail' : '/statics/api/config/vmDetail.json',
	'/cloudVendor/checkName' : '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/cloudVendor/lock' : '/statics/api/config/supplier.json',
	'/cloudVendor/active' : '/statics/api/config/supplier.json',
	'/cloudVendor/listAccounts' :'/statics/api/config/identity.json',
	'/region/list':'/statics/api/userCenter/group/group.json',

	//"/cloudVendor/listAll": '/statics/api/config/vmCount.json',
	//命令授权
	'/command/list': '/statics/api/config/command.json',
	'/command/create': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/command/modify': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/command/remove': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/command/detail' : '/statics/api/config/command-detail.json',
	//云主机管理
	"/vm/list": '/statics/api/config/vmList.json',
	'/vm/create': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/modify': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/remove': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/detail' : '/statics/api/config/vmDetail.json',
	'/vm/snapshoot' : '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/pause' : '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/suspend' : '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/active' : '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/restart' : '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/backup' : '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/recovery' : '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/start' : '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/stop' : '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/vm/sync':'/statics/api/assets/volume/volume-list.json',
	'/res/event/list':'/statics/api/assets/volume/volume-list.json',
	'/image/listName':'/statics/api/assets/volume/volume-list.json',
	'/list/listVersion':'/statics/api/assets/volume/volume-list.json',
	'/flavor/listFlavor':'/statics/api/userCenter/group/group.json',

	//计量计费
	  //价格
	'/modulePrice/list' : '/statics/api/measure/price.json',
	'/modulePrice/create' : '/statics/api/measure/price.json',
	'/modulePrice/modify':'/statics/api/measure/price.json',
	'/modulePrice/remove':'/statics/api/measure/price.json',
	  //资源计量
	'/modulePrice/meatureDepart':'/statics/api/measure/meterCloud.json',
	//'/department/list':'/statics/api/measure/meterUser.json',
	'/user/listByDid':'/statics/api/measure/meterUser.json',
	'/modulePrice/meatureUser':'/statics/api/measure/meterList.json',
	  //租户计量
	//'/tenant/list':'/statics/api/measure/meterUserList.json',
	'/modulePrice/meatureTenant':'/statics/api/measure/meterList.json',
	//日志
	'/log/audit/list' : '/statics/api/log/list.json',
	'/log/sys/list' : '/statics/api/log/yunxinglist.json',
	'/logplugin/list': '/statics/api/log/pluginList.json',
	'/logplugin/create': '/statics/api/alarm/alarmList.json',
	'/logplugin/modify': '/statics/api/alarm/alarmList.json',
	'/logplugin/remove': '/statics/api/alarm/alarmList.json',
	'/logplugin/detail': '/statics/api/log/pluginDetail.json',
	'/logsource/list': '/statics/api/log/sourceList.json',
	'/logsource/create': '/statics/api/alarm/alarmList.json',
	'/logsource/modify': '/statics/api/alarm/alarmList.json',
	'/logsource/remove': '/statics/api/alarm/alarmList.json',
	'/logsource/detail': '/statics/api/log/sourceDetail.json',
	'/logsource/upload': '/statics/api/log/sourceDetail.json',
	'/logsource/record/list':'/statics/api/monitor/measurement/measurement-list.json',
	'/logsource/record/remove':'/statics/api/monitor/measurement/measurement-list.json',
	'/logsource/record/detail':'/statics/api/log/sourceDetail-record.json',
	//运维中心
	'/stats/task':'/statics/api/operation/dashborad.json',
	'/target/server/list':'/statics/api/operation/serversList.json',
	'/task/graph/create': '/statics/api/operation/taskList.json',
	'/task/execute': '/statics/api/operation/taskList.json',
	'/task/graph/execute': '/statics/api/operation/taskList.json',
	'/task/graph/active': '/statics/api/operation/taskList.json',
	'/task/graph/cancel': '/statics/api/operation/taskList.json',
	'/backup/create': '/statics/api/operation/taskDetail.json',
	'/task/graph/detail': '/statics/api/operation/editDetail.json',
	'/task/graph/clone': '/statics/api/operation/editDetail.json',
	'/task/graph/modify': '/statics/api/operation/editDetail.json',
	'/task/graph/list': '/statics/api/operation/taskList.json',
	'/task/graph/recover':'/statics/api/operation/historyList.json',
	'/task/graph/remove': '/statics/api/operation/historyList.json',
	'/task/graph/start': '/statics/api/operation/taskDetail.json',
	'/record/graph/list':'/statics/api/operation/historyList.json',
	'/record/graph/task':'/statics/api/operation/taskDetail.json',
	'/record/graph/job': '/statics/api/operation/scriptDetail.json',
	'/record/results':'/statics/api/operation/resultList.json',
	'/record/graph/results':'/statics/api/operation/resultList.json',
	'/record/list':'/statics/api/operation/historyList.json',
	'/record/task':'/statics/api/operation/taskDetail.json',
	'/record/job': '/statics/api/operation/scriptDetail.json',
	'/record/graph/check': '/statics/api/operation/scriptDetail.json',
	'/record/graph/successes':'/statics/api/operation/serversList.json',
	'/user/checkUser':'/statics/api/operation/taskList.json',
	//定时作业
	'/cron/list': '/statics/api/operation/timedOperation.json',
	'/cron/create': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/cron/modify': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/cron/remove': '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/cron/detail' : '/statics/api/operation/timedOperation-detail.json',
	'/cron/active' : '/statics/api/assets/datacenter/dataCenter-modify.json',
	'/cron/suspend' : '/statics/api/assets/datacenter/dataCenter-modify.json',
	//应用
	'/app/list': '/statics/api/application/applicationList.json',
	'/app/basic': '/statics/api/application/appDetail.json',
	'/app/resources': '/statics/api/application/serversList.json',
	'/app/allocate': '/statics/api/operation/serversList.json',
	'/app/resource/remove': '/statics/api/operation/serversList.json',
	'/app/resource/update': '/statics/api/operation/serversList.json',
	'/app/detail': '/statics/api/application/appDetail.json',
	'/app/records': '/statics/api/operation/historyList.json',
	"/app/create" : "/statics/api/assets/room/roomList.json",
	"/app/modify" : "/statics/api/assets/room/roomList.json",
	"/app/remove" : "/statics/api/assets/room/roomList.json",
	"/app/build" : "/statics/api/assets/room/roomList.json",
	"/app/deploy/create" : "/statics/api/assets/room/roomList.json",
	"/app/execute" : "/statics/api/assets/room/roomList.json",
	"/app/bindAlarm" : "/statics/api/assets/room/roomList.json",
	"/app/bindDispatch" : "/statics/api/assets/room/roomList.json",
	//持续集成
	'/ci/tool/list' : '/statics/api/application/ciTool/ciToolList.json',
	'/ci/tool/modify' : '/statics/api/application/ciTool/ciToolList.json',
	'/ci/tool/create' : '/statics/api/application/ciTool/ciToolList.json',
	'/ci/tool/remove' : '/statics/api/application/ciTool/ciToolList.json',
	'/ci/tool/detail' : '/statics/api/application/ciTool/ciToolDetail.json',
	'/ci/tool/sync' : '/statics/api/application/ciTool/ciToolList.json',
	'/ci/job/list' : '/statics/api/application/ciTool/ciJobList.json',
	'/ci/job/build': '/statics/api/application/ciTool/ciJobList.json',
	//告警
	'/alarm/list': '/statics/api/alarm/alarmList.json',
	'/alarm/confirm': '/statics/api/alarm/alarmList.json',
	'/alarm/solve': '/statics/api/alarm/alarmList.json',
	'/alarm/remove': '/statics/api/alarm/alarmList.json',
	'/alarm/detail': '/statics/api/alarm/alarmDetail.json',
	'/alarm/strategy/list': '/statics/api/alarm/alarmSList.json',
	'/alarm/strategy/detail': '/statics/api/alarm/alarmSDetail.json',
	'/alarm/strategy/create': '/statics/api/alarm/alarmSList.json',
	'/alarm/strategy/modify': '/statics/api/alarm/alarmSList.json',
	'/alarm/strategy/remove': '/statics/api/alarm/alarmSList.json',
	'/alarm/strategy/record/list':'/statics/api/monitor/measurement/measurement-list.json',
	'/alarm/strategy/record/remove':'/statics/api/monitor/measurement/measurement-list.json',
	'/alarm/strategy/record/detail':'/statics/api/alarm/alarmSDetail-record.json',
	'/alarm/strategy/upload': '/statics/api/alarm/alarmSList.json',
	'/dispatch/strategy/list': '/statics/api/alarm/assignList.json',
	'/dispatch/strategy/create': '/statics/api/alarm/alarmSList.json',
	'/dispatch/strategy/modify': '/statics/api/alarm/alarmSList.json',
	'/dispatch/strategy/remove': '/statics/api/alarm/alarmSList.json',
	'/dispatch/strategy/detail': '/statics/api/alarm/assignDetail.json',
	'/notice/strategy/list': '/statics/api/alarm/noticeList.json',
	'/notice/strategy/create': '/statics/api/alarm/noticeList.json',
	'/notice/strategy/modify': '/statics/api/alarm/noticeList.json',
	'/notice/strategy/remove': '/statics/api/alarm/noticeList.json',
	'/notice/strategy/detail': '/statics/api/alarm/noticeDetail.json',
	'/notice/strategy/users':'/statics/api/alarm/noticeUser.json',
	'/notice/strategy/binds': '/statics/api/alarm/noticeList.json',
	'/statics/api/alarm/measurementData.json': '/statics/api/alarm/measurementData.json',
	
	"/statics/api/dashborad/dashborad.json":"/statics/api/dashborad/dashborad.json",
	"/topology/data":"/statics/api/topology/topology.json",

	//监控-数据纵览
	'/snmp/connect':'/statics/api/monitor/topology/connect.json',
	'/snmp/device':'/statics/api/monitor/topology/device.json',
	//数据中心监控
	'/monitor/dc/query' : '/statics/api/monitor/host/cpu.json',
	//机房监控
	'/monitor/room/query' : '/statics/api/monitor/host/cpu.json',
	//机柜监控
	//'/monitor/rack/query' : '/statics/api/monitor/host/cpu.json',
	//主机监控
	'/monitor/server/query' : '/statics/api/monitor/host/cpu.json',
	//虚机监控
	'/monitor/vm/query' : '/statics/api/monitor/host/cpu.json',
	//监控查询
	'/monitor/query' : '/statics/api/monitor/query/cpu.json',
	'/monitor/getMeasurementTypes' : '/statics/api/monitor/query/item.json',
	//监控分析
	'/monitor/report/list':'/statics/api/monitor/analysis/default.json',
	'/monitor/report/export':'/statics/api/monitor/analysis/default.json',
	'/monitor/queryTrend':'/statics/api/monitor/query/cpu.json',
	'monitor/report/trend':'/statics/api/monitor/analysis/default.json',
	//资源监控
	'/monitor/queryEquipmentAllType':'/statics/api/monitor/resource/treemenu.json',
	'/monitor/status/query':'/statics/api/config/vmList.json',
	'/monitor/chart/view':'/statics/api/monitor/query/cpu.json',
	'/monitor/queryEquipment':'/statics/api/config/vmList.json',
	//监控项管理
	'/measure/list':'/statics/api/monitor/measurement/measurement-list.json',
	'/measure/create':'/statics/api/monitor/measurement/measurement-list.json',
	'/measure/upload':'/statics/api/monitor/measurement/measurement-list.json',
	'/measure/modify':'/statics/api/monitor/measurement/measurement-list.json',
	'/measure/remove':'/statics/api/monitor/measurement/measurement-list.json',
	'/measure/detail':'/statics/api/monitor/measurement/measurement-detail.json',
	'/measure/item/list':'/statics/api/monitor/measurement/measurement-list.json',
	'/measure/item/create':'/statics/api/monitor/measurement/measurement-list.json',
	'/measure/item/modify':'/statics/api/monitor/measurement/measurement-list.json',
	'/measure/item/remove':'/statics/api/monitor/measurement/measurement-list.json',
	'/measure/record/list':'/statics/api/monitor/measurement/measurement-list.json',
	'/measure/record/remove':'/statics/api/monitor/measurement/measurement-list.json',
	'/measure/item/detail':'/statics/api/monitor/measurement/measurement-detail.json',
	'/measure/plugin/create':'/statics/api/monitor/measurement/measurement-list.json',
	'/measure/plugin/modify':'/statics/api/monitor/measurement/measurement-list.json',
	'/measure/plugin/detail':'/statics/api/monitor/measurement/measurement-detail.json',
	'/measure/record/detail':'/statics/api/monitor/measurement/measurement-record.json',
	'/measure/uploadInterval':'/statics/api/monitor/measurement/measurement-list.json',
	//自动管理
	'/statics/api/autos/machine/machine-list.json':'/statics/api/autos/machine/machine-list.json',

	//个人中心
	'/message/list': '/statics/api/personal/messageList.json',
	'/message/remove': '/statics/api/alarm/alarmList.json',
	'/message/detail': '/statics/api/personal/messageDetail.json',
	//流程中心
	'/apply/list': '/statics/api/process/applyList.json',
	'/apply/remove': '/statics/api/alarm/alarmList.json',
	'/apply/detail': '/statics/api/process/applyDetail.json',
	'/apply/create': '/statics/api/alarm/alarmList.json',
	'/apply/approve': '/statics/api/alarm/alarmList.json',
	'/apply/refuse': '/statics/api/alarm/alarmList.json',
});